### ISSUE TITLE
i

### ISSUE THREAD

**Issue by Amir-Hossein-Azimi** [ShahramHosseinzadeh/RubinNews#1]
سلام اقای حسینی زاده من هم مثل شما از دانشجویان روبین هستم .

**Comment by ShahramHosseinzadeh** [comment]
سلام آقای عظیمی خوشبختم🌹

‫‪Amir Hossein Azimi‬‏ ***@***.***‬‏> در تاریخ شنبه ۲۵ مارس
۲۰۲۳ ساعت ۱۶:۲۷ نوشت:‬
